# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lvecchia <lvecchia@student.42barcel>       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/04/16 10:26:17 by lvecchia          #+#    #+#              #
#    Updated: 2023/04/16 20:50:04 by brandebr         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = rush-02

FLAGS = -Wall -Wextra -Werror 

SRC = main.c

$(NAME):
	cc $(FLAGS) $(SRC) -o $(NAME)

clean: 
	/bin/rm -f *.o 

fclean: clean
	/bin/rm -f $(NAME)

re: fclean all

	 

